name = "globe-radio"
main = "dist/worker.js"
compatibility_date = "2024-01-01"

[assets]
directory = "dist"
binding = "ASSETS"

# Default configuration
[env.default]
name = "globe-radio"
pattern = "gradio.clothpath.com/*"
zone_name = "clothpath.com"
